name: example
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: saibotma <email@example.com>

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  angular: ^6.0.1
  tio_angular_components:
    path: ..

dev_dependencies:
  build_runner: ^1.10.11
  build_test: ^1.3.2
  build_web_compilers: ^2.12.0
  pedantic: ^1.9.2
