name: tio_angular_components
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://tio-design.github.io/

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  angular: ^6.0.1
  observable: ^0.22.2
  angular_components: ^1.0.2
  logging: ^0.11.4

dev_dependencies:
  pedantic: ^1.9.2
