name: tio_angular_components
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: tobias <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  angular: ^5.2.0
  observable: ^0.22.1+3
  angular_components: ^0.11.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
